export const GET_ADMIN_ORDER_REQUEST = "GET_ADMIN_ORDER_REQUEST;"
export const GET_ADMIN_ORDER_FAIL = "GET_ADMIN_ORDER_FAIL";
export const GET_ADMIN_ORDER_SUCCESS = "GET_ADMIN_ORDER_SUCCESS";

export const ADMIN_DELETE_ORDER_REQUEST = "ADMIN_DELETE_ORDER_REQUEST;"
export const ADMIN_DELETE_ORDER_FAIL = "ADMIN_DELETE_ORDER_FAIL";
export const ADMIN_DELETE_ORDER_SUCCESS = "ADMIN_DELETE_ORDER_SUCCESS";
export const ADMIN_DELETE_ORDER_RESET = "ADMIN_DELETE_ORDER_RESET";

export const ADMIN_UPDATE_ORDER_REQUEST = "ADMIN_UPDATE_ORDER_REQUEST;"
export const ADMIN_UPDATE_ORDER_FAIL = "ADMIN_UPDATE_ORDER_FAIL";
export const ADMIN_UPDATE_ORDER_SUCCESS = "ADMIN_UPDATE_ORDER_SUCCESS";
export const ADMIN_UPDATE_ORDER_RESET = "ADMIN_UPDATE_ORDER_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";