export const ADMIN_ALL_PRODUCT_REQUEST = "ADMIN_ALL_PRODUCT_REQUEST;"
export const ADMIN_ALL_PRODUCT_FAIL = "ADMIN_ALL_PRODUCT_FAIL";
export const ADMIN_ALL_PRODUCT_SUCCESS = "ADMIN_ALL_PRODUCT_SUCCESS";

export const ADMIN_PRODUCT_REVIEW_REQUEST = "ADMIN_PRODUCT_REVIEW_REQUEST;"
export const ADMIN_PRODUCT_REVIEW_FAIL = "ADMIN_PRODUCT_REVIEW_FAIL";
export const ADMIN_PRODUCT_REVIEW_SUCCESS = "ADMIN_PRODUCT_REVIEW_SUCCESS";

export const ADMIN_DELETE_PRODUCT_REVIEW_REQUEST = "ADMIN_DELETE_PRODUCT_REVIEW_REQUEST;"
export const ADMIN_DELETE_PRODUCT_REVIEW_FAIL = "ADMIN_DELETE_PRODUCT_REVIEW_FAIL";
export const ADMIN_DELETE_PRODUCT_REVIEW_SUCCESS = "ADMIN_DELETE_PRODUCT_REVIEW_SUCCESS";
export const ADMIN_DELETE_PRODUCT_REVIEW_RESET = "ADMIN_DELETE_PRODUCT_REVIEW_RESET";

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST;"
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_RESET = "ADMIN_DELETE_PRODUCT_RESET";

export const ADMIN_NEW_PRODUCT_REQUEST = "ADMIN_NEW_PRODUCT_REQUEST;"
export const ADMIN_NEW_PRODUCT_FAIL = "ADMIN_NEW_PRODUCT_FAIL";
export const ADMIN_NEW_PRODUCT_SUCCESS = "ADMIN_NEW_PRODUCT_SUCCESS";
export const ADMIN_NEW_PRODUCT_RESET = "ADMIN_NEW_PRODUCT_RESET";

export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST;"
export const ADMIN_UPDATE_PRODUCT_FAIL = "ADMIN_UPDATE_PRODUCT_FAIL";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_RESET = "ADMIN_UPDATE_PRODUCT_RESET";

export const ADMIN_UPDATE_PRODUCT_IMAGES_REQUEST = "ADMIN_UPDATE_PRODUCT_IMAGES_REQUEST;"
export const ADMIN_UPDATE_PRODUCT_IMAGES_FAIL = "ADMIN_UPDATE_PRODUCT_IMAGES_FAIL";
export const ADMIN_UPDATE_PRODUCT_IMAGES_SUCCESS = "ADMIN_UPDATE_PRODUCT_IMAGES_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_IMAGES_RESET = "ADMIN_UPDATE_PRODUCT_IMAGES_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";