export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST;"
export const ADMIN_ALL_USERS_FAIL = "ADMIN_ALL_USERS_FAIL";
export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS";

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST;"
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_RESET = "ADMIN_DELETE_USER_RESET";

export const ADMIN_GET_USER_DETAILS_REQUEST = "ADMIN_GET_USER_DETAILS_REQUEST;"
export const ADMIN_GET_USER_DETAILS_FAIL = "ADMIN_GET_USER_DETAILS_FAIL";
export const ADMIN_GET_USER_DETAILS_SUCCESS = "ADMIN_GET_USER_DETAILS_SUCCESS";

export const ADMIN_UPDATE_USER_DETAILS_REQUEST = "ADMIN_UPDATE_USER_DETAILS_REQUEST;"
export const ADMIN_UPDATE_USER_DETAILS_FAIL = "ADMIN_UPDATE_USER_DETAILS_FAIL";
export const ADMIN_UPDATE_USER_DETAILS_SUCCESS = "ADMIN_UPDATE_USER_DETAILS_SUCCESS";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";