export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST;"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";

export const RESET_FORGOT_PASSWORD_REQUEST = "RESET_FORGOT_PASSWORD_REQUEST;"
export const RESET_FORGOT_PASSWORD_FAIL = "RESET_FORGOT_PASSWORD_FAIL";
export const RESET_FORGOT_PASSWORD_SUCCESS = "RESET_FORGOT_PASSWORD_SUCCESS";

export const CLEAR_ERROR = "CLEAR_ERROR";