export const CREATE_NEW_ORDER_REQUEST = "CREATE_NEW_ORDER_REQUEST";
export const CREATE_NEW_ORDER_FAIL = "CREATE_NEW_ORDER_FAIL";
export const CREATE_NEW_ORDER_SUCCESS = "CREATE_NEW_ORDER_SUCCESS";

export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST;"
export const GET_USER_ORDER_FAIL = "GET_USER_ORDER_FAIL";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";

export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST;"
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";


export const CLEAR_ERROR = "CLEAR_ERROR";
